### ISSUE TITLE
Create diagrams for sensor measurements

### ISSUE THREAD

**Issue by janwirwahn** [mpfeil/OpenSenseMap#2]
Display current day by default. Nice feature would be a time slider to change time resolution on x-axis.

**Comment by janwirwahn** [comment]
Simple visualization for time series should be sufficient for now.

**Comment by mpfeil** [comment]
Was implemented by @AlexIsHappy in c36c3840b53f2d87cbe2a6ef8907531b12d3fa36 and is now online
