### ISSUE TITLE
option for adding a photo of SenseBox setup

### ISSUE THREAD

**Issue by robarto** [mpfeil/OpenSenseMap#22]
to see what kind of case the users used and how (high / close to wall / exposed to sun) they have mounted the box.

**Comment by robarto** [comment]
geil! congrats! schon ausgerollt?

On Mon, Feb 16, 2015 at 3:01 PM, Matthias Pfeil <notifications@github.com>
wrote:

> Closed #22 <https://github.com/mpfeil/OpenSenseMap/issues/22> via fd6bc58
> <https://github.com/mpfeil/OpenSenseMap/commit/fd6bc580756f5c1ad80b77ca48daaf43a762d30a>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mpfeil/OpenSenseMap/issues/22#event-236328392>.
>



-- 
--

Thomas Bartoschek
ifgi - Institute for Geoinformatics
University of Münster
Heisenbergstr. 2
48149 Münster, Germany

Phone:  +49 (0)251 83 30011
Mobile: +49 (0)173 511 6094
Fax:    +49 (0)251 83 39763

Email: bartoschek@uni-muenster.de
http://ifgi.uni-muenster.de/
http://www.gi-at-school.de/
http://vespucci.org/

**Comment by mpfeil** [comment]
nein noch nicht. kommt heute nacht
